# Generated by Django 5.2.1 on 2025-06-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Локация'),
        ),
    ]
