# Generated by Django 5.2.1 on 2025-06-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_and_answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответы', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
