# Generated by Django 4.2 on 2025-06-07 12:53

from django.db import migrations, models
import logo.models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=logo.models.category_image_path),
        ),
    ]
