# Generated by Django 4.2 on 2025-06-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options_alter_favoriteproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={},
        ),
        migrations.AlterField(
            model_name='productsize',
            name='title',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=10),
        ),
    ]
