# Generated by Django 5.2.1 on 2025-06-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerimage',
            options={'verbose_name': 'Баннер-фото', 'verbose_name_plural': 'Баннер-фото'},
        ),
        migrations.AlterModelOptions(
            name='mainpagecard',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='mainpagecontent',
            options={'verbose_name': 'Главный-баннер', 'verbose_name_plural': 'Главный-баннер'},
        ),
        migrations.AlterModelOptions(
            name='mainpageservicecard',
            options={'verbose_name': 'Баннеры-карты', 'verbose_name_plural': 'Баннеры'},
        ),
    ]
