# Generated by Django 4.2 on 2025-06-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация-места', 'verbose_name_plural': 'Локация-места'},
        ),
    ]
