# Generated by Django 5.2.1 on 2025-06-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Добавить_Видео', 'verbose_name_plural': 'Добавить_Видео'},
        ),
    ]
