# Generated by Django 5.2.1 on 2025-06-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_title', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytitle',
            options={'verbose_name': 'Катерогия_техта', 'verbose_name_plural': 'Катерогия_техта'},
        ),
    ]
